
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_math-videos
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
